#!/usr/bin/env bash
# configure Nginx so that its HTTP response contains a custom header
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://x.com/;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart


