#!/usr/bin/env bash
# Allows incoming traffic on port 80 so that our nginx server can listen on that port
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
